# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uncertainty_engine_resource_client.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.IsolatedAsyncioTestCase):
    """TemplatesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TemplatesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_workflow_template(self) -> None:
        """Test case for delete_workflow_template

        Delete Workflow Template
        """
        pass

    async def test_get_workflow_template_record(self) -> None:
        """Test case for get_workflow_template_record

        Get Workflow Template
        """
        pass

    async def test_get_workflow_template_records(self) -> None:
        """Test case for get_workflow_template_records

        Get Workflow Templates
        """
        pass

    async def test_workflow_template(self) -> None:
        """Test case for workflow_template

        Workflow Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
