# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uncertainty_engine_resource_client.api.account_records_api import AccountRecordsApi


class TestAccountRecordsApi(unittest.IsolatedAsyncioTestCase):
    """AccountRecordsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AccountRecordsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_account_record(self) -> None:
        """Test case for delete_account_record

        Delete Account Record
        """
        pass

    async def test_get_account_record(self) -> None:
        """Test case for get_account_record

        Get Account Record Id
        """
        pass

    async def test_get_account_record_projects(self) -> None:
        """Test case for get_account_record_projects

        Get Account Record Projects
        """
        pass

    async def test_post_account_record(self) -> None:
        """Test case for post_account_record

        Post Account Record
        """
        pass


if __name__ == '__main__':
    unittest.main()
