# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from my_api_client.models.workflow_version_response import WorkflowVersionResponse

class TestWorkflowVersionResponse(unittest.TestCase):
    """WorkflowVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowVersionResponse:
        """Test WorkflowVersionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowVersionResponse`
        """
        model = WorkflowVersionResponse()
        if include_optional:
            return WorkflowVersionResponse(
                workflow_version_record = my_api_client.models.workflow_version_record.WorkflowVersionRecord(
                    _id = '', 
                    name = '', 
                    project_id = '', 
                    workflow_id = '', 
                    owner_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    location = my_api_client.models.resource_location.ResourceLocation(
                        id = null, 
                        storage_type = '', 
                        config = my_api_client.models.config.Config(), ), ),
                workflow = my_api_client.models.workflow.Workflow()
            )
        else:
            return WorkflowVersionResponse(
                workflow_version_record = my_api_client.models.workflow_version_record.WorkflowVersionRecord(
                    _id = '', 
                    name = '', 
                    project_id = '', 
                    workflow_id = '', 
                    owner_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    location = my_api_client.models.resource_location.ResourceLocation(
                        id = null, 
                        storage_type = '', 
                        config = my_api_client.models.config.Config(), ), ),
                workflow = my_api_client.models.workflow.Workflow(),
        )
        """

    def testWorkflowVersionResponse(self):
        """Test WorkflowVersionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
