# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uncertainty_engine_resource_client.api.auth_api import AuthApi


class TestAuthApi(unittest.IsolatedAsyncioTestCase):
    """AuthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AuthApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_tokens(self) -> None:
        """Test case for get_tokens

        Get Tokens
        """
        pass

    async def test_refresh_token(self) -> None:
        """Test case for refresh_token

        Refresh Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
