# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from my_api_client.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.IsolatedAsyncioTestCase):
    """WorkflowsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WorkflowsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_workflow_record(self) -> None:
        """Test case for delete_workflow_record

        Delete Workflow
        """
        pass

    async def test_delete_workflow_version_record(self) -> None:
        """Test case for delete_workflow_version_record

        Delete Workflow Version
        """
        pass

    async def test_get_latest_workflow_version(self) -> None:
        """Test case for get_latest_workflow_version

        Get Latest Workflow Version
        """
        pass

    async def test_get_project_workflow_records(self) -> None:
        """Test case for get_project_workflow_records

        Get Project Workflow Records
        """
        pass

    async def test_get_workflow_record(self) -> None:
        """Test case for get_workflow_record

        Get Workflow Record
        """
        pass

    async def test_get_workflow_version(self) -> None:
        """Test case for get_workflow_version

        Get Workflow Version
        """
        pass

    async def test_get_workflow_version_records(self) -> None:
        """Test case for get_workflow_version_records

        Get Workflow Version Records
        """
        pass

    async def test_post_workflow_record(self) -> None:
        """Test case for post_workflow_record

        Post Workflow Record
        """
        pass

    async def test_post_workflow_version(self) -> None:
        """Test case for post_workflow_version

        Post Workflow Version
        """
        pass

    async def test_put_workflow_version(self) -> None:
        """Test case for put_workflow_version

        Put Workflow Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
