# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uncertainty_engine_resource_client.api.project_records_api import ProjectRecordsApi


class TestProjectRecordsApi(unittest.TestCase):
    """ProjectRecordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectRecordsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_project_record(self) -> None:
        """Test case for delete_project_record

        Delete Project Record
        """
        pass

    def test_get_project_record_id(self) -> None:
        """Test case for get_project_record_id

        Get Project Record Id
        """
        pass

    def test_patch_project_record(self) -> None:
        """Test case for patch_project_record

        Patch Project Record Name
        """
        pass

    def test_post_project_record(self) -> None:
        """Test case for post_project_record

        Post Project Record
        """
        pass


if __name__ == '__main__':
    unittest.main()
