# Configuration file for OpenAPI Generator
generatorName: python
inputSpec: http://uncert-loadb-tyhgijrbhk8m-992006005.eu-west-2.elb.amazonaws.com/openapi.json  # Location of the OpenAPI spec
outputDir: .  # Directory to generate the code in

packageName: uncertainty_engine_resource_client # Name of client package
gitRepoId: uncertainty-engine-resource-client # Name of the git repository
gitHost: github.com # Host for the git repository
gitUserId: digiLab-ai # User ID for the git repository
minimalUpdate: true  # Only write files that have changed

additionalProperties:
  library: urllib3  # Use asyncio for async support

globalProperties:
  modelTests: "false" # Disable generation of model tests
